name: SEND_MSG

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Generate Mattermost message
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "{\"text\":\"Pull Request Opened: $(echo $GITHUB_CONTEXT | jq -r '.event.pull_request._links.html.href')\"}" > mattermost.json

    - uses: cpanato/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
